python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_lossless_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt --output_script_filename decode_iiif_ht_lossless_plt_cbk_64,64.sh  --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_lossless_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_ht_lossless_plt_cbk_64,64.sh    --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_lossy_3bpp_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt --output_script_filename decode_iiif_ht_lossy_3bpp_plt_cbk_64,64.sh  --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_lossy_3bpp_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_ht_lossy_3bpp_plt_cbk_64,64.sh    --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_lossless_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt --output_script_filename decode_iiif_j2k1_lossless_plt_cbk_64,64.sh  --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_lossless_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_j2k1_lossless_plt_cbk_64,64.sh    --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_lossy_3bpp_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt --output_script_filename decode_iiif_j2k1_lossy_3bpp_plt_cbk_64,64.sh  --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_lossy_3bpp_plt_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_j2k1_lossy_3bpp_plt_cbk_64,64.sh    --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_digital_bodelian_lossless_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt   --output_script_filename decode_iiif_htj2k_digital_bodelian_lossless_codeblock_64,64.sh --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_digital_bodelian_lossless_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_htj2k_digital_bodelian_lossless_codeblock_64,64.sh     --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_digital_bodelian_lossy_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt   --output_script_filename decode_iiif_htj2k_digital_bodelian_lossy_codeblock_64,64.sh --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/htj2k_digital_bodelian_lossy_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_htj2k_digital_bodelian_lossy_codeblock_64,64.sh     --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jph

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_digital_bodelian_lossless_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt   --output_script_filename decode_iiif_j2k1_digital_bodelian_lossless_codeblock_64,64.sh --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_digital_bodelian_lossless_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_j2k1_digital_bodelian_lossless_codeblock_64,64.sh     --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2

python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_digital_bodelian_lossy_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/iiif_urls.txt   --output_script_filename decode_iiif_j2k1_digital_bodelian_lossy_codeblock_64,64.sh --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2  
python ../source/convert_iiif_urls_to_kdu_buffered_expand.py --compressed_directory ../../compressed/j2k1_digital_bodelian_lossy_codeblock_64,64/  --iiif_urls_filename ../resources/iiif_urls/uv_urls.txt   --output_script_filename decode_uv_j2k1_digital_bodelian_lossy_codeblock_64,64.sh     --number_of_decoding_cycle_iterations 5 --compressed_file_extension .jp2



